pipeline {

    agent any

    environment {
        PASS = credentials('registry-pass')
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                    ./jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./jenkins/build/build.sh

                '''
            }
        }

        stage('Test') {
            steps {
                 echo "Test the job"
            }
        }

        stage('Push') {
            steps {
                echo "push the docker image in docker hub"
            }
        }

        stage('Deploy') {
            steps {
                echo "deploy the image"
            }
        }
    }
}
